package heuristic

import (
	"os"
	"strings"
)

// ReadFileHead читает первые n строк файла, максимум 4KB.
func ReadFileHead(path string, lines int) string {
	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() {
		return ""
	}

	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()

	bufPtr := BufPool.Get().(*[]byte)
	buf := *bufPtr
	defer BufPool.Put(bufPtr)

	n, _ := f.Read(buf)
	content := string(buf[:n])

	var result strings.Builder
	count := 0
	for _, line := range strings.Split(content, "\n") {
		if count >= lines {
			break
		}
		result.WriteString(line)
		result.WriteString("\n")
		count++
	}
	return strings.TrimRight(result.String(), "\n")
}

// HasGeneratedMarker проверяет первые строки файла на маркеры генерации.
func HasGeneratedMarker(head string) bool {
	lower := strings.ToLower(head)
	preciseMarkers := []string{
		"code generated by",
		"generated by protoc",
		"protoc-gen-go",
		"protoc-gen-grpc",
		"this file was generated",
		"this is a generated file",
		"@generated",
		"generated by go generate",
		"generated by mockgen",
		"generated by swagger",
		"generated by flatc",
		"generated by thrift",
	}
	for _, m := range preciseMarkers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	if strings.Contains(lower, "do not edit") {
		if strings.Contains(lower, "generated") || strings.Contains(lower, "auto") {
			return true
		}
		genNames := []string{"protoc", "protoc-gen", "go generate", "mockgen",
			"swagger", "flatc", "thrift", "wire", "stringer"}
		for _, g := range genNames {
			if strings.Contains(lower, g) {
				return true
			}
		}
	}
	return false
}

// HasSpecMarker проверяет содержимое на признаки API-спецификаций.
func HasSpecMarker(head string) bool {
	definiteMarkers := []string{
		`"openapi"`, `"swagger"`,
		`openapi:`, `swagger:`,
		`syntax = "proto`, `syntax='proto`,
		`"asyncapi"`, `"raml"`,
		`__schema`,
	}
	for _, m := range definiteMarkers {
		if strings.Contains(head, m) {
			return true
		}
	}

	comboMarkers := []string{
		`"paths"`, `"definitions"`, `"components"`,
		`paths:`, `definitions:`,
	}
	found := 0
	for _, m := range comboMarkers {
		if strings.Contains(head, m) {
			found++
		}
	}
	return found >= 2
}
