package heuristic

import (
	"os"
	"path/filepath"
	"testing"
)

func TestPreScreen_KeepsBusinessLogic(t *testing.T) {
	// Create temp directory with test files
	tmp := t.TempDir()

	// Create test files
	testFiles := []struct {
		path     string
		content  string
		wantKeep bool
	}{
		// Business logic - should be kept
		{"src/user.controller.ts", "export class UserController {}", true},
		{"src/order.service.ts", "export class OrderService {}", true},
		{"src/product.repository.ts", "export class ProductRepository {}", true},
		{"src/auth.handler.ts", "export class AuthHandler {}", true},
		{"src/data.dto.ts", "export class DataDTO {}", true},
		{"src/user.entity.ts", "export class UserEntity {}", true},

		// Test files - should be kept
		{"src/user.controller.spec.ts", "describe('User', () => {})", true},
		{"src/order.service.test.ts", "test('Order', () => {})", true},
		{"src_test/user_test.go", "func TestUser(t *testing.T) {}", true},

		// Generated files - should be ignored
		{"src/generated.pb.ts", "// Code generated by protoc", false},
		{"src/auto_gen.go", "// Code generated by go generate", false},

		// Regular source files - should be kept
		{"src/main.ts", "export function main() {}", true},
		{"src/handler.go", "func Handler() {}", true},
	}

	for _, tf := range testFiles {
		fullPath := filepath.Join(tmp, tf.path)
		os.MkdirAll(filepath.Dir(fullPath), 0755)
		os.WriteFile(fullPath, []byte(tf.content), 0644)
	}

	// Collect relative paths
	var files []string
	filepath.Walk(tmp, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(tmp, path)
		files = append(files, rel)
		return nil
	})

	// Run PreScreen
	result := PreScreen(files, tmp)

	// Check results
	keptPatterns := make(map[string]bool)
	for _, f := range result.AutoKept {
		keptPatterns[f] = true
	}

	ignoredPatterns := make(map[string]bool)
	for _, e := range result.AutoIgnored {
		ignoredPatterns[e.Path] = true
	}

	for _, tf := range testFiles {
		if tf.wantKeep {
			if !keptPatterns[tf.path] && !containsRemaining(result.Remaining, tf.path) {
				t.Errorf("Expected %s to be kept, but it was ignored", tf.path)
			}
		} else {
			if !ignoredPatterns[tf.path] {
				t.Errorf("Expected %s to be ignored, but it was kept", tf.path)
			}
		}
	}
}

func containsRemaining(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return true // If not explicitly ignored, it goes to remaining (kept for LLM)
}

func TestIsSafeCompound_NestJS(t *testing.T) {
	// NestJS patterns that should be safe
	safePatterns := []string{
		"*.controller.ts",
		"*.controller.js",
		"*.service.ts",
		"*.service.js",
		"*.repository.ts",
		"*.handler.ts",
		"*.adapter.ts",
		"*.interceptor.ts",
		"*.guard.ts",
		"*.pipe.ts",
		"*.middleware.ts",
		"*.dto.ts",
		"*.entity.ts",
		"*.model.ts",
		"*.schema.ts",
	}

	for _, pattern := range safePatterns {
		if !IsSafeCompound(pattern) {
			t.Errorf("Expected %s to be safe compound pattern", pattern)
		}
	}
}

func TestCompoundPattern_NestJS(t *testing.T) {
	tests := []struct {
		filename string
		want     string
	}{
		{"user.controller.ts", "*.controller.ts"},
		{"order.service.ts", "*.service.ts"},
		{"product.repository.ts", "*.repository.ts"},
		{"auth.handler.ts", "*.handler.ts"},
		{"data.dto.ts", "*.dto.ts"},
		{"user.entity.ts", "*.entity.ts"},
		{"main.ts", ""},       // Not compound
		{"config.ts", ""},     // Not compound
	}

	for _, tt := range tests {
		got := CompoundPattern(tt.filename)
		if got != tt.want {
			t.Errorf("CompoundPattern(%q) = %q, want %q", tt.filename, got, tt.want)
		}
	}
}
