// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package postgres

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchInsertASTUnits = `-- name: BatchInsertASTUnits :batchone
INSERT INTO ast_units (repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id
`

type BatchInsertASTUnitsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertASTUnitsParams struct {
	RepoID    string
	FilePath  string
	Language  string
	Kind      string
	Name      string
	Qualified string
	ParentID  *int64
	StartLine int32
	EndLine   int32
	StartByte int32
	EndByte   int32
	Signature string
	Doc       string
	Hash      string
	Meta      string
}

func (q *Queries) BatchInsertASTUnits(ctx context.Context, arg []BatchInsertASTUnitsParams) *BatchInsertASTUnitsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RepoID,
			a.FilePath,
			a.Language,
			a.Kind,
			a.Name,
			a.Qualified,
			a.ParentID,
			a.StartLine,
			a.EndLine,
			a.StartByte,
			a.EndByte,
			a.Signature,
			a.Doc,
			a.Hash,
			a.Meta,
		}
		batch.Queue(batchInsertASTUnits, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertASTUnitsBatchResults{br, len(arg), false}
}

func (b *BatchInsertASTUnitsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *BatchInsertASTUnitsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertEdges = `-- name: BatchInsertEdges :batchone
INSERT INTO edges (repo_id, src_id, dst_id, kind, dst_name, file_path, line, dst_repo_id, confidence, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type BatchInsertEdgesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertEdgesParams struct {
	RepoID     string
	SrcID      int64
	DstID      int64
	Kind       string
	DstName    string
	FilePath   string
	Line       int32
	DstRepoID  string
	Confidence float32
	Meta       string
}

func (q *Queries) BatchInsertEdges(ctx context.Context, arg []BatchInsertEdgesParams) *BatchInsertEdgesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RepoID,
			a.SrcID,
			a.DstID,
			a.Kind,
			a.DstName,
			a.FilePath,
			a.Line,
			a.DstRepoID,
			a.Confidence,
			a.Meta,
		}
		batch.Queue(batchInsertEdges, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertEdgesBatchResults{br, len(arg), false}
}

func (b *BatchInsertEdgesBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *BatchInsertEdgesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
