// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgdb

import (
	"context"
)

const batchUpdateEdgeResolutions = `-- name: BatchUpdateEdgeResolutions :many
UPDATE edges e
SET dst_id = v.dst_id, dst_repo_id = v.dst_repo_id, confidence = v.confidence
FROM (
    SELECT unnest($1::bigint[]) AS id,
           unnest($2::bigint[]) AS dst_id,
           unnest($3::text[]) AS dst_repo_id,
           unnest($4::real[]) AS confidence
) AS v
WHERE e.id = v.id
RETURNING e.id
`

type BatchUpdateEdgeResolutionsParams struct {
	Ids         []int64
	DstIds      []int64
	DstRepoIds  []string
	Confidences []float32
}

// BatchUpdateEdgeResolutions applies a whole batch of resolutions in one
// statement, joined against the arrays as if against a temp table: linking a
// large repository resolves millions of edges and one UPDATE each serializes
// the pass on the writer. It returns the ids it actually updated, so the
// caller can attribute the missing ones to the edges that no longer exist.
func (q *Queries) BatchUpdateEdgeResolutions(ctx context.Context, arg BatchUpdateEdgeResolutionsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, batchUpdateEdgeResolutions,
		arg.Ids,
		arg.DstIds,
		arg.DstRepoIds,
		arg.Confidences,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNextIndexJob = `-- name: ClaimNextIndexJob :one
UPDATE index_jobs
SET status = 'running', claimed_by = $1, claimed_at = $2, heartbeat_at = $2
WHERE id = (
    SELECT id FROM index_jobs WHERE status = 'pending'
    ORDER BY id LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by, payload
`

type ClaimNextIndexJobParams struct {
	ClaimedBy string
	ClaimedAt int64
}

type ClaimNextIndexJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       bool
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
	Payload     string
}

// ClaimNextIndexJob atomically claims the oldest pending job. FOR UPDATE SKIP
// LOCKED lets concurrent instances claim different jobs without blocking each
// other, which is what makes the queue safe for multiple workers.
func (q *Queries) ClaimNextIndexJob(ctx context.Context, arg ClaimNextIndexJobParams) (ClaimNextIndexJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextIndexJob, arg.ClaimedBy, arg.ClaimedAt)
	var i ClaimNextIndexJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
		&i.Payload,
	)
	return i, err
}

const claimRepoForIndexing = `-- name: ClaimRepoForIndexing :execrows
UPDATE repos
SET status = $1, last_error = '',
    claimed_by = $2, claim_expires_at = $3
WHERE id = $4
  AND (status <> $1 OR claim_expires_at <= $5)
`

type ClaimRepoForIndexingParams struct {
	Status         string
	ClaimedBy      string
	ClaimExpiresAt int64
	ID             string
	Now            int64
}

// ClaimRepoForIndexing takes the claim when the repo is not indexing or when
// the previous owner's claim has expired, so a crashed indexer cannot wedge
// the repo in "indexing" forever.
func (q *Queries) ClaimRepoForIndexing(ctx context.Context, arg ClaimRepoForIndexingParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimRepoForIndexing,
		arg.Status,
		arg.ClaimedBy,
		arg.ClaimExpiresAt,
		arg.ID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIndexJob = `-- name: CompleteIndexJob :execrows
UPDATE index_jobs SET status = $1, error = $2, payload = '' WHERE id = $3 AND status = 'running' AND claimed_by = $4
`

type CompleteIndexJobParams struct {
	Status    string
	Error     string
	ID        int64
	ClaimedBy string
}

// The payload dies with the result: a terminal job is never re-run, and keeping
// every applied commit batch would grow this table by the size of the
// repository's history.
func (q *Queries) CompleteIndexJob(ctx context.Context, arg CompleteIndexJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIndexJob,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.ClaimedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countASTUnits = `-- name: CountASTUnits :one
SELECT COUNT(*) FROM ast_units
`

func (q *Queries) CountASTUnits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countASTUnits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countASTUnitsByRepo = `-- name: CountASTUnitsByRepo :one
SELECT COUNT(*) FROM ast_units WHERE repo_id = $1
`

func (q *Queries) CountASTUnitsByRepo(ctx context.Context, repoID string) (int64, error) {
	row := q.db.QueryRow(ctx, countASTUnitsByRepo, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteASTUnitsByFile = `-- name: DeleteASTUnitsByFile :exec
DELETE FROM ast_units WHERE repo_id = $1 AND file_path = $2
`

type DeleteASTUnitsByFileParams struct {
	RepoID   string
	FilePath string
}

func (q *Queries) DeleteASTUnitsByFile(ctx context.Context, arg DeleteASTUnitsByFileParams) error {
	_, err := q.db.Exec(ctx, deleteASTUnitsByFile, arg.RepoID, arg.FilePath)
	return err
}

const deleteASTUnitsByFiles = `-- name: DeleteASTUnitsByFiles :exec
DELETE FROM ast_units WHERE repo_id = $1 AND file_path = ANY($2::text[])
`

type DeleteASTUnitsByFilesParams struct {
	RepoID string
	Paths  []string
}

func (q *Queries) DeleteASTUnitsByFiles(ctx context.Context, arg DeleteASTUnitsByFilesParams) error {
	_, err := q.db.Exec(ctx, deleteASTUnitsByFiles, arg.RepoID, arg.Paths)
	return err
}

const deleteASTUnitsByKind = `-- name: DeleteASTUnitsByKind :exec
DELETE FROM ast_units WHERE repo_id = $1 AND kind = $2
`

type DeleteASTUnitsByKindParams struct {
	RepoID string
	Kind   string
}

func (q *Queries) DeleteASTUnitsByKind(ctx context.Context, arg DeleteASTUnitsByKindParams) error {
	_, err := q.db.Exec(ctx, deleteASTUnitsByKind, arg.RepoID, arg.Kind)
	return err
}

const deleteASTUnitsByRepo = `-- name: DeleteASTUnitsByRepo :exec
DELETE FROM ast_units WHERE repo_id = $1
`

func (q *Queries) DeleteASTUnitsByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.Exec(ctx, deleteASTUnitsByRepo, repoID)
	return err
}

const deleteEdgesByFile = `-- name: DeleteEdgesByFile :exec
DELETE FROM edges WHERE repo_id = $1 AND file_path = $2
`

type DeleteEdgesByFileParams struct {
	RepoID   string
	FilePath string
}

func (q *Queries) DeleteEdgesByFile(ctx context.Context, arg DeleteEdgesByFileParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesByFile, arg.RepoID, arg.FilePath)
	return err
}

const deleteEdgesByFiles = `-- name: DeleteEdgesByFiles :exec
DELETE FROM edges WHERE repo_id = $1 AND file_path = ANY($2::text[])
`

type DeleteEdgesByFilesParams struct {
	RepoID string
	Paths  []string
}

func (q *Queries) DeleteEdgesByFiles(ctx context.Context, arg DeleteEdgesByFilesParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesByFiles, arg.RepoID, arg.Paths)
	return err
}

const deleteEdgesByKind = `-- name: DeleteEdgesByKind :exec
DELETE FROM edges WHERE repo_id = $1 AND kind = $2
`

type DeleteEdgesByKindParams struct {
	RepoID string
	Kind   string
}

func (q *Queries) DeleteEdgesByKind(ctx context.Context, arg DeleteEdgesByKindParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesByKind, arg.RepoID, arg.Kind)
	return err
}

const deleteEdgesByKindAndDst = `-- name: DeleteEdgesByKindAndDst :exec
DELETE FROM edges WHERE kind = $1 AND dst_name = $2
`

type DeleteEdgesByKindAndDstParams struct {
	Kind    string
	DstName string
}

func (q *Queries) DeleteEdgesByKindAndDst(ctx context.Context, arg DeleteEdgesByKindAndDstParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesByKindAndDst, arg.Kind, arg.DstName)
	return err
}

const deleteEdgesByKindGlobal = `-- name: DeleteEdgesByKindGlobal :exec
DELETE FROM edges WHERE kind = $1
`

func (q *Queries) DeleteEdgesByKindGlobal(ctx context.Context, kind string) error {
	_, err := q.db.Exec(ctx, deleteEdgesByKindGlobal, kind)
	return err
}

const deleteEdgesByRepo = `-- name: DeleteEdgesByRepo :exec
DELETE FROM edges WHERE repo_id = $1
`

func (q *Queries) DeleteEdgesByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.Exec(ctx, deleteEdgesByRepo, repoID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE repo_id = $1 AND path = $2
`

type DeleteFileParams struct {
	RepoID string
	Path   string
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.Exec(ctx, deleteFile, arg.RepoID, arg.Path)
	return err
}

const deleteFilesByRepo = `-- name: DeleteFilesByRepo :exec
DELETE FROM files WHERE repo_id = $1
`

func (q *Queries) DeleteFilesByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.Exec(ctx, deleteFilesByRepo, repoID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const getASTUnitByID = `-- name: GetASTUnitByID :one
SELECT id, repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta
FROM ast_units WHERE id = $1
`

func (q *Queries) GetASTUnitByID(ctx context.Context, id int64) (AstUnit, error) {
	row := q.db.QueryRow(ctx, getASTUnitByID, id)
	var i AstUnit
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.FilePath,
		&i.Language,
		&i.Kind,
		&i.Name,
		&i.Qualified,
		&i.ParentID,
		&i.StartLine,
		&i.EndLine,
		&i.StartByte,
		&i.EndByte,
		&i.Signature,
		&i.Doc,
		&i.Hash,
		&i.Meta,
	)
	return i, err
}

const getASTUnitsByIDs = `-- name: GetASTUnitsByIDs :many
SELECT id, repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta
FROM ast_units WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetASTUnitsByIDs(ctx context.Context, ids []int64) ([]AstUnit, error) {
	rows, err := q.db.Query(ctx, getASTUnitsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AstUnit
	for rows.Next() {
		var i AstUnit
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.FilePath,
			&i.Language,
			&i.Kind,
			&i.Name,
			&i.Qualified,
			&i.ParentID,
			&i.StartLine,
			&i.EndLine,
			&i.StartByte,
			&i.EndByte,
			&i.Signature,
			&i.Doc,
			&i.Hash,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT repo_id, path, language, hash, size, mod_time, indexed
FROM files WHERE repo_id = $1 AND path = $2
`

type GetFileParams struct {
	RepoID string
	Path   string
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile, arg.RepoID, arg.Path)
	var i File
	err := row.Scan(
		&i.RepoID,
		&i.Path,
		&i.Language,
		&i.Hash,
		&i.Size,
		&i.ModTime,
		&i.Indexed,
	)
	return i, err
}

const getFilesByRepo = `-- name: GetFilesByRepo :many
SELECT repo_id, path, language, hash, size, mod_time, indexed
FROM files WHERE repo_id = $1
`

func (q *Queries) GetFilesByRepo(ctx context.Context, repoID string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.RepoID,
			&i.Path,
			&i.Language,
			&i.Hash,
			&i.Size,
			&i.ModTime,
			&i.Indexed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexJob = `-- name: GetIndexJob :one
SELECT id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
FROM index_jobs WHERE id = $1
`

type GetIndexJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       bool
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

func (q *Queries) GetIndexJob(ctx context.Context, id int64) (GetIndexJobRow, error) {
	row := q.db.QueryRow(ctx, getIndexJob, id)
	var i GetIndexJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos WHERE id = $1
`

type GetRepoRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        bool
}

func (q *Queries) GetRepo(ctx context.Context, id string) (GetRepoRow, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i GetRepoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Url,
		&i.Path,
		&i.Branch,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.IndexedAt,
		&i.LastCommit,
		&i.PendingCommit,
		&i.Active,
	)
	return i, err
}

const hasPendingCommitJobBefore = `-- name: HasPendingCommitJobBefore :one
SELECT EXISTS(
    SELECT 1 FROM index_jobs
    WHERE repo_id = $1 AND kind = 'commits' AND status IN ('pending', 'running') AND id < $2
)
`

type HasPendingCommitJobBeforeParams struct {
	RepoID string
	ID     int64
}

// HasPendingCommitJobBefore backs the "wait or give up" decision of a commit
// batch that does not continue the repo's cursor. Served by idx_index_jobs_repo.
func (q *Queries) HasPendingCommitJobBefore(ctx context.Context, arg HasPendingCommitJobBeforeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingCommitJobBefore, arg.RepoID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeatIndexJob = `-- name: HeartbeatIndexJob :execrows
UPDATE index_jobs SET heartbeat_at = $1 WHERE id = $2 AND status = 'running' AND claimed_by = $3
`

type HeartbeatIndexJobParams struct {
	HeartbeatAt int64
	ID          int64
	ClaimedBy   string
}

// Heartbeat/Complete/Release are scoped to the claiming worker: a worker whose
// job was requeued and re-claimed elsewhere must not overwrite the new owner's
// result (that is how a successful run got recorded as "repo busy").
func (q *Queries) HeartbeatIndexJob(ctx context.Context, arg HeartbeatIndexJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatIndexJob, arg.HeartbeatAt, arg.ID, arg.ClaimedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertASTUnit = `-- name: InsertASTUnit :one

INSERT INTO ast_units (repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id
`

type InsertASTUnitParams struct {
	RepoID    string
	FilePath  string
	Language  string
	Kind      string
	Name      string
	Qualified string
	ParentID  *int64
	StartLine int32
	EndLine   int32
	StartByte int32
	EndByte   int32
	Signature string
	Doc       string
	Hash      string
	Meta      string
}

// --- AST units ---
func (q *Queries) InsertASTUnit(ctx context.Context, arg InsertASTUnitParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertASTUnit,
		arg.RepoID,
		arg.FilePath,
		arg.Language,
		arg.Kind,
		arg.Name,
		arg.Qualified,
		arg.ParentID,
		arg.StartLine,
		arg.EndLine,
		arg.StartByte,
		arg.EndByte,
		arg.Signature,
		arg.Doc,
		arg.Hash,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCommitJob = `-- name: InsertCommitJob :one
INSERT INTO index_jobs (repo_id, kind, force, status, created_at, payload)
VALUES ($1, 'commits', FALSE, 'pending', $2, $3)
RETURNING id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
`

type InsertCommitJobParams struct {
	RepoID    string
	CreatedAt int64
	Payload   string
}

type InsertCommitJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       bool
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

// InsertCommitJob never merges with a queued job: each batch is a distinct
// span of history, and dropping one would leave a hole nothing reports.
func (q *Queries) InsertCommitJob(ctx context.Context, arg InsertCommitJobParams) (InsertCommitJobRow, error) {
	row := q.db.QueryRow(ctx, insertCommitJob, arg.RepoID, arg.CreatedAt, arg.Payload)
	var i InsertCommitJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
	)
	return i, err
}

const insertEdge = `-- name: InsertEdge :one

INSERT INTO edges (repo_id, src_id, dst_id, kind, dst_name, file_path, line, dst_repo_id, confidence, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertEdgeParams struct {
	RepoID     string
	SrcID      int64
	DstID      int64
	Kind       string
	DstName    string
	FilePath   string
	Line       int32
	DstRepoID  string
	Confidence float32
	Meta       string
}

// --- Edges ---
func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEdge,
		arg.RepoID,
		arg.SrcID,
		arg.DstID,
		arg.Kind,
		arg.DstName,
		arg.FilePath,
		arg.Line,
		arg.DstRepoID,
		arg.Confidence,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIndexJob = `-- name: InsertIndexJob :one


INSERT INTO index_jobs (repo_id, kind, force, status, created_at)
VALUES ($1, 'index', $2, 'pending', $3)
ON CONFLICT (repo_id) WHERE status = 'pending' AND kind = 'index'
DO UPDATE SET force = index_jobs.force OR EXCLUDED.force
RETURNING id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
`

type InsertIndexJobParams struct {
	RepoID    string
	Force     bool
	CreatedAt int64
}

type InsertIndexJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       bool
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

// --- Index jobs ---
// The payload (a commit job's batch, file contents included) is deliberately
// absent from every projection but ClaimNextIndexJob's: only the worker that
// runs the job needs it, and it can be tens of megabytes.
// InsertIndexJob upserts against the partial unique index over pending index
// rows, so concurrent enqueues cannot create duplicates and a queued job
// absorbs the request instead of dropping its force flag.
func (q *Queries) InsertIndexJob(ctx context.Context, arg InsertIndexJobParams) (InsertIndexJobRow, error) {
	row := q.db.QueryRow(ctx, insertIndexJob, arg.RepoID, arg.Force, arg.CreatedAt)
	var i InsertIndexJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
	)
	return i, err
}

const listActiveRepos = `-- name: ListActiveRepos :many
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos WHERE active ORDER BY created_at
`

type ListActiveReposRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        bool
}

func (q *Queries) ListActiveRepos(ctx context.Context) ([]ListActiveReposRow, error) {
	rows, err := q.db.Query(ctx, listActiveRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveReposRow
	for rows.Next() {
		var i ListActiveReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Url,
			&i.Path,
			&i.Branch,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.LastCommit,
			&i.PendingCommit,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexJobs = `-- name: ListIndexJobs :many
SELECT id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
FROM index_jobs WHERE repo_id = $1 ORDER BY id DESC LIMIT $2
`

type ListIndexJobsParams struct {
	RepoID string
	Limit  int32
}

type ListIndexJobsRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       bool
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

func (q *Queries) ListIndexJobs(ctx context.Context, arg ListIndexJobsParams) ([]ListIndexJobsRow, error) {
	rows, err := q.db.Query(ctx, listIndexJobs, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexJobsRow
	for rows.Next() {
		var i ListIndexJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Kind,
			&i.Force,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.HeartbeatAt,
			&i.ClaimedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos ORDER BY created_at
`

type ListReposRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        bool
}

func (q *Queries) ListRepos(ctx context.Context) ([]ListReposRow, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReposRow
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Url,
			&i.Path,
			&i.Branch,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.LastCommit,
			&i.PendingCommit,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseIndexJob = `-- name: ReleaseIndexJob :execrows
UPDATE index_jobs AS ij
SET status = 'pending', claimed_by = '', claimed_at = 0, heartbeat_at = 0
WHERE ij.id = $1 AND ij.status = 'running' AND ij.claimed_by = $2
  AND (
      ij.kind <> 'index'
      OR NOT EXISTS (
          SELECT 1 FROM index_jobs p
          WHERE p.repo_id = ij.repo_id AND p.status = 'pending' AND p.kind = 'index'
      )
  )
`

type ReleaseIndexJobParams struct {
	ID        int64
	ClaimedBy string
}

// A released index job whose slot was taken meanwhile is dropped as superseded
// by the caller; a commit job is always requeued, since no other job carries
// its batch.
func (q *Queries) ReleaseIndexJob(ctx context.Context, arg ReleaseIndexJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIndexJob, arg.ID, arg.ClaimedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const repoExists = `-- name: RepoExists :one
SELECT EXISTS(SELECT 1 FROM repos WHERE id = $1)
`

func (q *Queries) RepoExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, repoExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const requeueStaleIndexJobs = `-- name: RequeueStaleIndexJobs :execrows
UPDATE index_jobs
SET status = 'pending', claimed_by = '', claimed_at = 0, heartbeat_at = 0
WHERE status = 'running' AND heartbeat_at < $1
`

func (q *Queries) RequeueStaleIndexJobs(ctx context.Context, heartbeatAt int64) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleIndexJobs, heartbeatAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetExpiredIndexingRepos = `-- name: ResetExpiredIndexingRepos :execrows
UPDATE repos SET status = 'idle', claimed_by = '', claim_expires_at = 0,
    pending_commit = '', last_error = $1
WHERE status = 'indexing' AND claim_expires_at <= $2
`

type ResetExpiredIndexingReposParams struct {
	LastError string
	Now       int64
}

func (q *Queries) ResetExpiredIndexingRepos(ctx context.Context, arg ResetExpiredIndexingReposParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetExpiredIndexingRepos, arg.LastError, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetIndexingRepos = `-- name: ResetIndexingRepos :execrows
UPDATE repos SET status = 'idle', claimed_by = '', claim_expires_at = 0,
    pending_commit = '', last_error = $1
WHERE status = 'indexing'
`

func (q *Queries) ResetIndexingRepos(ctx context.Context, lastError string) (int64, error) {
	result, err := q.db.Exec(ctx, resetIndexingRepos, lastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveRepos = `-- name: SetActiveRepos :exec
UPDATE repos SET active = (id = ANY($1::text[]))
`

// SetActiveRepos replaces the whole working set in one statement: every row is
// raised or cleared by the same UPDATE, so no reader can observe a half-applied
// switch. Ids naming no repository simply match nothing, and an empty array
// leaves nothing active.
func (q *Queries) SetActiveRepos(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, setActiveRepos, ids)
	return err
}

const setRepoPendingCommit = `-- name: SetRepoPendingCommit :execrows
UPDATE repos SET pending_commit = $1 WHERE id = $2
`

type SetRepoPendingCommitParams struct {
	PendingCommit string
	ID            string
}

func (q *Queries) SetRepoPendingCommit(ctx context.Context, arg SetRepoPendingCommitParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRepoPendingCommit, arg.PendingCommit, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeFile = `-- name: StoreFile :exec


INSERT INTO files (repo_id, path, language, hash, size, mod_time, indexed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repo_id, path) DO UPDATE SET
    language = EXCLUDED.language, hash = EXCLUDED.hash,
    size = EXCLUDED.size, mod_time = EXCLUDED.mod_time, indexed = EXCLUDED.indexed
`

type StoreFileParams struct {
	RepoID   string
	Path     string
	Language string
	Hash     string
	Size     int64
	ModTime  int64
	Indexed  bool
}

// Static queries for the PostgreSQL backend, compiled by sqlc into the pgdb
// package. Dynamic filtered queries (GetASTUnits/GetEdges over QueryOpts) are
// built with sqlutil in postgres.go instead; sqlc cannot express them.
// --- Files ---
func (q *Queries) StoreFile(ctx context.Context, arg StoreFileParams) error {
	_, err := q.db.Exec(ctx, storeFile,
		arg.RepoID,
		arg.Path,
		arg.Language,
		arg.Hash,
		arg.Size,
		arg.ModTime,
		arg.Indexed,
	)
	return err
}

const storeRepo = `-- name: StoreRepo :exec

INSERT INTO repos (id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, source = EXCLUDED.source, url = EXCLUDED.url,
    path = EXCLUDED.path, branch = EXCLUDED.branch
`

type StoreRepoParams struct {
	ID         string
	Name       string
	Source     string
	Url        string
	Path       string
	Branch     string
	Status     string
	LastError  string
	CreatedAt  int64
	IndexedAt  int64
	LastCommit string
}

// --- Repos ---
// StoreRepo only writes the repo's definition on conflict. Re-registering an
// existing repo must not reset status/indexed_at/last_commit: that would allow
// a second concurrent index pass and disable the commit-gap guard. The active
// column is absent from both halves for the same kind of reason: an insert
// takes the schema's default (active) and a re-registration leaves the working
// set SetActiveRepos decided.
func (q *Queries) StoreRepo(ctx context.Context, arg StoreRepoParams) error {
	_, err := q.db.Exec(ctx, storeRepo,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Url,
		arg.Path,
		arg.Branch,
		arg.Status,
		arg.LastError,
		arg.CreatedAt,
		arg.IndexedAt,
		arg.LastCommit,
	)
	return err
}

const supersedeStaleIndexJobs = `-- name: SupersedeStaleIndexJobs :execrows
UPDATE index_jobs AS ij
SET status = 'error', error = 'superseded by a pending job for the same repo'
WHERE ij.status = 'running' AND ij.heartbeat_at < $1 AND ij.kind = 'index'
  AND (
      EXISTS (SELECT 1 FROM index_jobs p
              WHERE p.repo_id = ij.repo_id AND p.status = 'pending' AND p.kind = 'index')
      OR ij.id <> (
          SELECT MIN(j.id) FROM index_jobs j
          WHERE j.repo_id = ij.repo_id AND j.status = 'running'
            AND j.heartbeat_at < $1 AND j.kind = 'index'
      )
  )
`

// Only one index job per repo may become pending, so stale running ones that
// would collide are failed as superseded before the survivor is requeued.
// Commit jobs are exempt: they are not interchangeable.
func (q *Queries) SupersedeStaleIndexJobs(ctx context.Context, cutoff int64) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeStaleIndexJobs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unresolveEdgesByDstFile = `-- name: UnresolveEdgesByDstFile :execrows
UPDATE edges SET dst_id = 0, dst_repo_id = ''
WHERE dst_id <> 0
  AND dst_id IN (
      SELECT u.id FROM ast_units u WHERE u.repo_id = $1 AND u.file_path = $2
  )
`

type UnresolveEdgesByDstFileParams struct {
	RepoID   string
	FilePath string
}

// UnresolveEdgesByDstFile clears the resolution of every edge pointing at a
// unit of the given file. Re-indexing recreates the file's units with new IDs,
// so an edge keeping the old one reads as resolved while resolving to nothing.
// The subquery is served by idx_ast_units_repo_file and the update by
// idx_edges_dst, so the cost follows the file's units, not the edge table.
func (q *Queries) UnresolveEdgesByDstFile(ctx context.Context, arg UnresolveEdgesByDstFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, unresolveEdgesByDstFile, arg.RepoID, arg.FilePath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unresolveEdgesByDstFiles = `-- name: UnresolveEdgesByDstFiles :execrows
UPDATE edges SET dst_id = 0, dst_repo_id = ''
WHERE dst_id <> 0
  AND dst_id IN (
      SELECT u.id FROM ast_units u
      WHERE u.repo_id = $1 AND u.file_path = ANY($2::text[])
  )
`

type UnresolveEdgesByDstFilesParams struct {
	RepoID string
	Paths  []string
}

// UnresolveEdgesByDstFiles is UnresolveEdgesByDstFile for a whole window of
// files, so re-indexing one window costs one statement rather than one per file.
func (q *Queries) UnresolveEdgesByDstFiles(ctx context.Context, arg UnresolveEdgesByDstFilesParams) (int64, error) {
	result, err := q.db.Exec(ctx, unresolveEdgesByDstFiles, arg.RepoID, arg.Paths)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEdgeDstName = `-- name: UpdateEdgeDstName :execrows
UPDATE edges SET dst_name = $1 WHERE id = $2
`

type UpdateEdgeDstNameParams struct {
	DstName string
	ID      int64
}

func (q *Queries) UpdateEdgeDstName(ctx context.Context, arg UpdateEdgeDstNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEdgeDstName, arg.DstName, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEdgeResolution = `-- name: UpdateEdgeResolution :execrows
UPDATE edges SET dst_id = $1, dst_repo_id = $2, confidence = $3 WHERE id = $4
`

type UpdateEdgeResolutionParams struct {
	DstID      int64
	DstRepoID  string
	Confidence float32
	ID         int64
}

func (q *Queries) UpdateEdgeResolution(ctx context.Context, arg UpdateEdgeResolutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEdgeResolution,
		arg.DstID,
		arg.DstRepoID,
		arg.Confidence,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRepoLastCommit = `-- name: UpdateRepoLastCommit :execrows
UPDATE repos SET last_commit = $1 WHERE id = $2
`

type UpdateRepoLastCommitParams struct {
	LastCommit string
	ID         string
}

func (q *Queries) UpdateRepoLastCommit(ctx context.Context, arg UpdateRepoLastCommitParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRepoLastCommit, arg.LastCommit, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRepoStatus = `-- name: UpdateRepoStatus :execrows
UPDATE repos SET status = $1, last_error = $2, indexed_at = $3,
    claimed_by = '', claim_expires_at = 0, pending_commit = ''
WHERE id = $4
`

type UpdateRepoStatusParams struct {
	Status    string
	LastError string
	IndexedAt int64
	ID        string
}

func (q *Queries) UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRepoStatus,
		arg.Status,
		arg.LastError,
		arg.IndexedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
