package builtin

import (
	"strings"
)

// GoPlugin implements plugin.Plugin for Go.
type GoPlugin struct{}

func (p *GoPlugin) Name() string { return "go" }

func (p *GoPlugin) Extensions() []string {
	return []string{".go"}
}

func (p *GoPlugin) IsTestFile(filename string) bool {
	return strings.HasSuffix(filename, "_test.go")
}

func (p *GoPlugin) IsGenerated(head string) bool {
	lower := strings.ToLower(head)
	markers := []string{
		"code generated by",
		"do not edit",
		"protoc-gen-go",
		"stringer",
		"mockgen",
	}
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}

func (p *GoPlugin) ExtractImports(lines []string) []string {
	var imports []string
	inImportBlock := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		// Single-line import
		if strings.HasPrefix(trimmed, "import ") {
			if strings.Contains(trimmed, "(") {
				inImportBlock = true
				continue
			}
			// import "path"
			if strings.Contains(trimmed, `"`) {
				parts := strings.Split(trimmed, `"`)
				if len(parts) >= 2 {
					imports = append(imports, parts[1])
				}
			}
		}

		// Import block
		if inImportBlock {
			if trimmed == ")" {
				inImportBlock = false
				continue
			}
			if strings.Contains(trimmed, `"`) {
				parts := strings.Split(trimmed, `"`)
				if len(parts) >= 2 {
					imports = append(imports, parts[1])
				}
			}
		}

		// Stop after imports section
		if strings.HasPrefix(trimmed, "func ") || strings.HasPrefix(trimmed, "type ") {
			break
		}

		if len(imports) >= 20 {
			break
		}
	}

	return imports
}

func (p *GoPlugin) ExtractSignatures(lines []string) []string {
	var sigs []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		// Function signatures
		if strings.HasPrefix(trimmed, "func ") {
			sig := trimmed
			if len(sig) > 100 {
				sig = sig[:100] + "..."
			}
			sigs = append(sigs, sig)
		}

		// Type declarations
		if strings.HasPrefix(trimmed, "type ") {
			sig := trimmed
			if len(sig) > 100 {
				sig = sig[:100] + "..."
			}
			sigs = append(sigs, sig)
		}

		if len(sigs) >= 10 {
			break
		}
	}
	return sigs
}

func (p *GoPlugin) ExtractSampleChunks(lines []string) []string {
	// Find first function or type declaration
	firstSig := -1
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "func ") || strings.HasPrefix(trimmed, "type ") {
			firstSig = i
			break
		}
	}

	if firstSig >= 0 {
		return []string{joinLines(lines, firstSig, 5)}
	}

	// Fallback: first 5 non-empty lines
	return firstNonEmpty(lines, 5)
}

// Helper functions
func joinLines(lines []string, start, count int) string {
	if start >= len(lines) {
		return ""
	}
	end := start + count
	if end > len(lines) {
		end = len(lines)
	}
	return strings.Join(lines[start:end], "\n")
}

func firstNonEmpty(lines []string, count int) []string {
	var result []string
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			result = append(result, line)
			if len(result) >= count {
				break
			}
		}
	}
	return result
}
