package builtin

import (
	"strings"
)

// JavaPlugin implements plugin.Plugin for Java.
type JavaPlugin struct{}

func (p *JavaPlugin) Name() string { return "java" }

func (p *JavaPlugin) Extensions() []string {
	return []string{".java"}
}

func (p *JavaPlugin) IsTestFile(filename string) bool {
	lower := strings.ToLower(filename)
	return strings.HasPrefix(lower, "test") ||
		strings.HasSuffix(lower, "test.java") ||
		strings.Contains(lower, "/test/") ||
		strings.Contains(lower, "/tests/")
}

func (p *JavaPlugin) IsGenerated(head string) bool {
	lower := strings.ToLower(head)
	markers := []string{
		"generated by",
		"auto-generated",
		"autogenerated",
		"do not edit",
		"@generated",
	}
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}

func (p *JavaPlugin) ExtractImports(lines []string) []string {
	var imports []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		// import statements
		if strings.HasPrefix(trimmed, "import ") {
			sig := trimmed
			if len(sig) > 120 {
				sig = sig[:120] + "..."
			}
			imports = append(imports, sig)
		}

		// Stop after imports (first class/interface declaration)
		if strings.HasPrefix(trimmed, "public class ") ||
			strings.HasPrefix(trimmed, "public interface ") ||
			strings.HasPrefix(trimmed, "class ") ||
			strings.HasPrefix(trimmed, "interface ") {
			break
		}

		if len(imports) >= 20 {
			break
		}
	}
	return imports
}

func (p *JavaPlugin) ExtractSignatures(lines []string) []string {
	var sigs []string
	keywords := []string{
		"public class ", "public interface ", "public enum ",
		"class ", "interface ", "enum ",
		"public ", "private ", "protected ",
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		for _, kw := range keywords {
			if strings.HasPrefix(trimmed, kw) {
				sig := trimmed
				if len(sig) > 100 {
					sig = sig[:100] + "..."
				}
				sigs = append(sigs, sig)
				break
			}
		}

		if len(sigs) >= 10 {
			break
		}
	}
	return sigs
}

func (p *JavaPlugin) ExtractSampleChunks(lines []string) []string {
	// Find first class or method declaration
	firstSig := -1
	keywords := []string{"class ", "interface ", "public ", "private ", "protected "}

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		for _, kw := range keywords {
			if strings.HasPrefix(trimmed, kw) {
				firstSig = i
				break
			}
		}
		if firstSig >= 0 {
			break
		}
	}

	if firstSig >= 0 {
		return []string{joinLines(lines, firstSig, 5)}
	}

	return firstNonEmpty(lines, 5)
}
