package builtin

import (
	"strings"
)

// PythonPlugin implements plugin.Plugin for Python.
type PythonPlugin struct{}

func (p *PythonPlugin) Name() string { return "python" }

func (p *PythonPlugin) Extensions() []string {
	return []string{".py"}
}

func (p *PythonPlugin) IsTestFile(filename string) bool {
	lower := strings.ToLower(filename)
	return strings.HasPrefix(lower, "test_") ||
		strings.HasSuffix(lower, "_test.py") ||
		strings.Contains(lower, "/tests/") ||
		strings.Contains(lower, "/test/")
}

func (p *PythonPlugin) IsGenerated(head string) bool {
	lower := strings.ToLower(head)
	markers := []string{
		"auto-generated",
		"autogenerated",
		"generated by",
		"do not edit",
		"# this file is generated",
	}
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}

func (p *PythonPlugin) ExtractImports(lines []string) []string {
	var imports []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments
		if strings.HasPrefix(trimmed, "#") {
			continue
		}

		// import statements
		if strings.HasPrefix(trimmed, "import ") || strings.HasPrefix(trimmed, "from ") {
			sig := trimmed
			if len(sig) > 120 {
				sig = sig[:120] + "..."
			}
			imports = append(imports, sig)
		}

		// Stop after imports section (first non-import, non-empty, non-comment line)
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") &&
			!strings.HasPrefix(trimmed, "import ") && !strings.HasPrefix(trimmed, "from ") &&
			!strings.HasPrefix(trimmed, "__") {
			break
		}

		if len(imports) >= 20 {
			break
		}
	}
	return imports
}

func (p *PythonPlugin) ExtractSignatures(lines []string) []string {
	var sigs []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		// Function definitions
		if strings.HasPrefix(trimmed, "def ") {
			sig := trimmed
			if len(sig) > 100 {
				sig = sig[:100] + "..."
			}
			sigs = append(sigs, sig)
		}

		// Class definitions
		if strings.HasPrefix(trimmed, "class ") {
			sig := trimmed
			if len(sig) > 100 {
				sig = sig[:100] + "..."
			}
			sigs = append(sigs, sig)
		}

		if len(sigs) >= 10 {
			break
		}
	}
	return sigs
}

func (p *PythonPlugin) ExtractSampleChunks(lines []string) []string {
	// Find first function or class definition
	firstSig := -1
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "def ") || strings.HasPrefix(trimmed, "class ") {
			firstSig = i
			break
		}
	}

	if firstSig >= 0 {
		return []string{joinLines(lines, firstSig, 5)}
	}

	return firstNonEmpty(lines, 5)
}
