package builtin

import (
	"strings"
)

// TypeScriptPlugin implements plugin.Plugin for TypeScript/JavaScript.
type TypeScriptPlugin struct{}

func (p *TypeScriptPlugin) Name() string { return "typescript" }

func (p *TypeScriptPlugin) Extensions() []string {
	return []string{".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"}
}

func (p *TypeScriptPlugin) IsTestFile(filename string) bool {
	lower := strings.ToLower(filename)
	return strings.HasSuffix(lower, ".test.ts") ||
		strings.HasSuffix(lower, ".test.tsx") ||
		strings.HasSuffix(lower, ".test.js") ||
		strings.HasSuffix(lower, ".test.jsx") ||
		strings.HasSuffix(lower, ".spec.ts") ||
		strings.HasSuffix(lower, ".spec.tsx") ||
		strings.HasSuffix(lower, ".spec.js") ||
		strings.HasSuffix(lower, ".spec.jsx")
}

func (p *TypeScriptPlugin) IsGenerated(head string) bool {
	lower := strings.ToLower(head)
	markers := []string{
		"@generated",
		"autogenerated",
		"auto-generated",
		"do not edit",
		"this file is generated",
	}
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}

func (p *TypeScriptPlugin) ExtractImports(lines []string) []string {
	var imports []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		// ES6 imports
		if strings.HasPrefix(trimmed, "import ") {
			sig := trimmed
			if len(sig) > 120 {
				sig = sig[:120] + "..."
			}
			imports = append(imports, sig)
		}

		// CommonJS require
		if strings.Contains(trimmed, "require(") {
			sig := trimmed
			if len(sig) > 120 {
				sig = sig[:120] + "..."
			}
			imports = append(imports, sig)
		}

		if len(imports) >= 20 {
			break
		}
	}
	return imports
}

func (p *TypeScriptPlugin) ExtractSignatures(lines []string) []string {
	var sigs []string
	keywords := []string{
		"export function ", "export const ", "export class ", "export interface ", "export type ",
		"function ", "const ", "class ", "interface ", "type ",
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip comments and empty lines
		if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
			continue
		}

		for _, kw := range keywords {
			if strings.HasPrefix(trimmed, kw) {
				sig := trimmed
				if len(sig) > 100 {
					sig = sig[:100] + "..."
				}
				sigs = append(sigs, sig)
				break
			}
		}

		if len(sigs) >= 10 {
			break
		}
	}
	return sigs
}

func (p *TypeScriptPlugin) ExtractSampleChunks(lines []string) []string {
	// Find first export or function declaration
	firstSig := -1
	keywords := []string{"export ", "function ", "class ", "interface ", "const "}

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		for _, kw := range keywords {
			if strings.HasPrefix(trimmed, kw) {
				firstSig = i
				break
			}
		}
		if firstSig >= 0 {
			break
		}
	}

	if firstSig >= 0 {
		return []string{joinLines(lines, firstSig, 5)}
	}

	return firstNonEmpty(lines, 5)
}
