package llm

import (
	"encoding/json"
	"fmt"
	"strings"

	"ragota/internal/analyze/types"
)

// BuildGroupEvaluationPrompt строит промпт для Pass 1: classify.
func BuildGroupEvaluationPrompt(groups []types.FileGroup, root string) string {
	var sb strings.Builder

	sb.WriteString(`You are evaluating file subgroups to determine if they should be excluded from AI code indexing.

For each subgroup, decide:
- "keep" — the files implement source code, business logic, tests, configs that define project structure
- "ignore" — the files are generated, API spec, documentation, data fixture, design asset, or infrastructure
- "confidence" — score 0-100 (100 = very sure, 50 = uncertain, 0 = no idea)

Respond with JSON array only, no markdown, no explanation:
[
  {"pattern": "k8s/*.yaml", "action": "ignore", "confidence": 95},
  {"pattern": "config/*.json", "action": "keep", "confidence": 80},
  ...
]

⚠️ CRITICAL FORMAT REQUIREMENTS:
- Each element MUST have exactly THREE fields: "pattern" (string), "action" (string), "confidence" (number)
- "pattern" must be a GLOB pattern (e.g., "*.yaml", "k8s/*", "**/*.json"), NOT an absolute file path
- DO NOT use "path", "extension", "size", "imports" or any other fields — ONLY "pattern", "action", "confidence"
- DO NOT return file metadata or detailed file information — ONLY the glob pattern and decision
- If you start outputting file paths or metadata, STOP and return to the correct format


CONCRETE EXAMPLES OF CORRECT DECISIONS:

KEEP (source/config/API boundaries):
  internal/handler.go → keep (business logic)
  api/handlers/user.go → keep (API boundary — cross-service calls)
  api/controllers/order.ts → keep (API boundary — HTTP endpoints)
  internal/api/payment/handler.go → keep (service boundary for cross-repo indexing)
  config/database.yaml → keep (runtime configuration)
  package.json → keep (project structure)
  README.md → keep (project overview)
  Makefile → keep (build automation)
  scripts/migrate.sh → keep (project tooling)
  src/utils.ts → keep (utility functions)
  tests/integration_test.go → keep (tests)
  api/proto/user.proto → keep (hand-written gRPC contract, NOT generated)
  schemas/payment.proto → keep (protobuf service definition for cross-repo gRPC)

IGNORE (generated/specs/infra/data/docs):
  api.swagger.json → ignore (API specification, not code)
  openapi/v1.yaml → ignore (API specification, not code)
  api/openapi.json → ignore (API specification, not code)
  k8s/deployment.yaml → ignore (infrastructure manifest)
  terraform/main.tf → ignore (infrastructure as code)
  docs/api-reference.md → ignore (documentation duplicating code)
  fixtures/seed.json → ignore (test data fixture)
  assets/logo.svg → ignore (design asset)
  CHANGELOG.md → ignore (release notes)
  .github/workflows/ci.yaml → ignore (CI/CD config)
  helm/values.yaml → ignore (deployment config)
  generated/models.go → ignore (generated code)

CRITERIA FOR IGNORE:
1. GENERATED — "DO NOT EDIT", "Code generated by", "protoc-gen-go"
2. SPECIFICATIONS — OpenAPI/Swagger JSON/YAML, GraphQL schemas (*.swagger.json, *.openapi.yaml)
3. INFRASTRUCTURE — Docker, K8s, Terraform, CI/CD, Helm
4. DATA — CSV, Excel, seed data, JSON fixtures, test datasets
5. DOCUMENTATION — large docs, changelogs, release notes, API reference docs
6. DEPRECATED — code in deprecated/archived/legacy directories
7. DESIGN — SVG exports, PlantUML, Mermaid diagrams

CRITERIA FOR KEEP:
- Regular source code implementing business logic
- API BOUNDARY CODE — handlers, controllers, endpoints (critical for cross-service indexing)
- Test files (_test.go, *.test.ts)
- Configuration files that define project structure
- README.md (project overview)

IMPORTANT: Never ignore repository root directories (containing go.mod, package.json, pom.xml, etc.)

SELF-REVIEW — Before outputting your final answer, double-check each decision for these common mistakes:
- Marking "*.json" as ignore when the group contains package.json, tsconfig.json (project structure files) → should be "keep"
- Marking "config/" as keep when most files are swagger.yaml or openapi specs → should be "ignore"
- Marking "*.yaml" as keep when most files are K8s manifests or Helm charts → should be "ignore"
- Marking "*.md" as ignore when it's the main README.md → should be "keep"
- Marking source code directories as ignore just because they contain some generated files → should be "keep"
- Marking "api/handlers/*.go" as ignore → WRONG! API boundary code must be kept for cross-repo indexing
- Marking "api/controllers/*.ts" as ignore → WRONG! Controller code is business logic, not API spec
- Marking "*.proto" as ignore → WRONG! Proto files are hand-written gRPC contracts, critical for cross-repo detection. They are NOT generated specs like swagger/openapi
- Confusing api/swagger.json (spec, ignore) with api/handlers/user.go (code, keep) → different!
- Confusing openapi/v1.yaml (spec, ignore) with schemas/user.proto (gRPC contract, keep) → different!

If you find a mistake in your initial assessment, correct it before outputting the final JSON array.
The output must be your FINAL, CORRECTED decisions.

`)

	fmt.Fprintf(&sb, "There are %d groups to evaluate:\n\n", len(groups))

	for i, g := range groups {
		// Если есть подгруппы, используем их
		if len(g.SubGroups) > 0 {
			fmt.Fprintf(&sb, "Group %d: %s (%d subgroups, %d total files)\n", i+1, g.Pattern, len(g.SubGroups), len(g.Files))
			for _, sg := range g.SubGroups {
				fmt.Fprintf(&sb, "  SubGroup: %s (%d files, %d samples)\n", sg.DirPath, len(sg.Files), len(sg.Samples))
				for _, s := range sg.Samples {
					writeTrimmedSample(&sb, s)
				}
			}
		} else {
			// Старый формат без подгрупп
			samples := SelectDiverseSamples(g.Files, 5, root)
			fmt.Fprintf(&sb, "Group %d: %s (%d files, dirs: %s)\n", i+1, g.Pattern, len(g.Files), strings.Join(g.Dirs, ", "))
			for _, s := range samples {
				writeTrimmedSample(&sb, s)
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("OUTPUT FORMAT RULES:\n")
	sb.WriteString("1. Start your response with the opening bracket [\n")
	sb.WriteString("2. End your response with the closing bracket ]\n")
	sb.WriteString("3. Do NOT use markdown code blocks (no triple backticks)\n")
	sb.WriteString("4. Do NOT add any text before or after the JSON array\n")
	sb.WriteString("5. Each element must have: \"pattern\", \"action\" (\"keep\" or \"ignore\"), \"confidence\" (0-100)\n")
	sb.WriteString("6. FORBIDDEN fields: \"path\", \"extension\", \"size\", \"imports\", \"flags\" — use ONLY pattern/action/confidence\n")
	sb.WriteString("7. Pattern must be a GLOB (e.g., \"*.go\", \"k8s/*\"), NOT an absolute path like \"/Users/...\"\n\n")
	sb.WriteString("Example of CORRECT output:\n")
	sb.WriteString("[\n")
	sb.WriteString("  {\"pattern\": \"k8s/*.yaml\", \"action\": \"ignore\", \"confidence\": 95},\n")
	sb.WriteString("  {\"pattern\": \"src/*.go\", \"action\": \"keep\", \"confidence\": 90}\n")
	sb.WriteString("]\n\n")
	sb.WriteString("Example of WRONG output (DO NOT DO THIS):\n")
	sb.WriteString("[\n")
	sb.WriteString("  {\"path\":\"/Users/.../file.go\",\"extension\":\".go\",\"size\":1234,...}  ← WRONG! Use pattern/action/confidence only!\n")
	sb.WriteString("]\n\n")
	sb.WriteString("Now respond with the FINAL JSON array. Start with [ and end with ].")

	return sb.String()
}

// maxSampleBytes — максимальный размер одного сэмпла в промпте (в байтах).
const maxSampleBytes = 2000

// writeTrimmedSample записывает сэмпл в промпт, обрезая чанки при необходимости.
func writeTrimmedSample(sb *strings.Builder, s types.FileMeta) {
	// Копируем и обрезаем чанки
	trimmed := s
	if len(trimmed.SampleChunks) > 0 {
		var limited []types.Chunk
		totalChunkBytes := 0
		for _, ch := range trimmed.SampleChunks {
			content := ch.Content
			// Обрезаем длинный чанк
			if len(content) > 500 {
				content = content[:500] + "...[truncated]"
			}
			// Ограничиваем общий размер чанков
			if totalChunkBytes+len(content) > 1500 {
				break
			}
			limited = append(limited, types.Chunk{
				Content:   content,
				StartLine: ch.StartLine,
				EndLine:   ch.EndLine,
				Position:  ch.Position,
			})
			totalChunkBytes += len(content)
		}
		trimmed.SampleChunks = limited
	}

	data, _ := json.Marshal(trimmed)
	if len(data) > maxSampleBytes {
		// Ещё один проход: обрезаем imports/signatures
		trimmed.Imports = trimmed.Imports[:min(3, len(trimmed.Imports))]
		trimmed.Signatures = trimmed.Signatures[:min(3, len(trimmed.Signatures))]
		data, _ = json.Marshal(trimmed)
	}
	sb.Write(data)
	sb.WriteString("\n")
}

// BuildContradictionPrompt строит промпт для Pass 2: contradiction check.
func BuildContradictionPrompt(decisions []types.GroupDecision, groups []types.FileGroup) string {
	var sb strings.Builder

	sb.WriteString(`You classified file groups for ignore/keep. Now check for contradictions and common mistakes:

COMMON MISTAKES:
- Marking "*.json" as ignore when it contains package.json, tsconfig.json (project structure)
- Marking "config/" as keep when it contains swagger.yaml (API spec)
- Marking "*.yaml" as keep when most files are K8s manifests
- Marking "*.md" as ignore when it's the main README

Review your decisions and correct any that seem wrong.

Respond with JSON array of CORRECTIONS only (groups you want to change):
[
  {"pattern": "*.json", "action": "keep", "confidence": 85, "reason": "contains package.json"},
  ...
]

If no corrections needed, respond with empty array: []

Your original decisions:
`)

	for _, d := range decisions {
		fmt.Fprintf(&sb, "  %s → %s (confidence: %d)\n", d.Pattern, d.Action, d.Confidence)
	}

	sb.WriteString("\nCorrections (or [] if none):\n")

	return sb.String()
}

// BuildDeepReviewPrompt строит промпт для Pass 3: deep review.
func BuildDeepReviewPrompt(group types.FileGroup, root string) string {
	var sb strings.Builder

	sb.WriteString(`You are reviewing a file group with low confidence. Examine the samples carefully and decide if they should share one rule or need different rules.

Compare these files:

`)

	// Если есть подгруппы, используем их
	var samples []types.FileMeta
	if len(group.SubGroups) > 0 {
		for _, sg := range group.SubGroups {
			samples = append(samples, sg.Samples...)
		}
	} else {
		samples = SelectDiverseSamples(group.Files, 10, root)
	}

	// Ограничиваем 10 файлами
	if len(samples) > 10 {
		samples = samples[:10]
	}

	for i, s := range samples {
		fmt.Fprintf(&sb, "FILE %d: %s\n", i+1, s.Path)
		if len(s.Flags) > 0 {
			fmt.Fprintf(&sb, "  Flags: %s\n", strings.Join(s.Flags, ", "))
		}
		if len(s.Imports) > 0 {
			fmt.Fprintf(&sb, "  Imports: %s\n", strings.Join(s.Imports[:min(5, len(s.Imports))], ", "))
		}
		// Выводим 3 чанка (начало/середина/конец)
		if len(s.SampleChunks) > 0 {
			sb.WriteString("  Content:\n")
			for _, chunk := range s.SampleChunks {
				sb.WriteString(fmt.Sprintf("    [%s, lines %d-%d]:\n", chunk.Position, chunk.StartLine, chunk.EndLine))
				for _, line := range strings.Split(chunk.Content, "\n") {
					sb.WriteString(fmt.Sprintf("      %s\n", line))
				}
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`
Decide:
- "keep" — these files are source code, tests, or important configs
- "ignore" — these files are generated, infrastructure, data, or documentation
- "confidence" — 0-100

Respond with JSON:
{"pattern": "...", "action": "keep|ignore", "confidence": 85}
`)

	return sb.String()
}
