// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type AstUnit struct {
	ID        int64
	RepoID    string
	FilePath  string
	Language  string
	Kind      string
	Name      string
	Qualified string
	ParentID  sql.NullInt64
	StartLine int64
	EndLine   int64
	StartByte int64
	EndByte   int64
	Signature string
	Doc       string
	Hash      string
	Meta      string
}

type Edge struct {
	ID         int64
	RepoID     string
	SrcID      int64
	DstID      int64
	Kind       string
	DstName    string
	FilePath   string
	Line       int64
	DstRepoID  string
	Confidence float64
	Meta       string
}

type File struct {
	RepoID   string
	Path     string
	Language string
	Hash     string
	Size     int64
	ModTime  int64
	Indexed  int64
}

type IndexJob struct {
	ID          int64
	RepoID      string
	Force       int64
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
	Kind        string
	Payload     string
}

type Repo struct {
	ID             string
	Name           string
	Source         string
	Url            string
	Path           string
	Branch         string
	Status         string
	LastError      string
	CreatedAt      int64
	IndexedAt      int64
	LastCommit     string
	ClaimedBy      string
	ClaimExpiresAt int64
	PendingCommit  string
	Active         int64
}

type RepoCoverage struct {
	RepoID     string
	Kind       string
	Candidates int64
	Edges      int64
	UpdatedAt  int64
}

type SchemaMigration struct {
	Version int64
}
