// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const claimRepoForIndexing = `-- name: ClaimRepoForIndexing :execrows
UPDATE repos
SET status = ?, last_error = '', claimed_by = ?, claim_expires_at = ?
WHERE id = ? AND (status != ? OR claim_expires_at <= ?)
`

type ClaimRepoForIndexingParams struct {
	Status           string
	ClaimedBy        string
	ClaimExpiresAt   int64
	ID               string
	Status_2         string
	ClaimExpiresAt_2 int64
}

func (q *Queries) ClaimRepoForIndexing(ctx context.Context, arg ClaimRepoForIndexingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRepoForIndexing,
		arg.Status,
		arg.ClaimedBy,
		arg.ClaimExpiresAt,
		arg.ID,
		arg.Status_2,
		arg.ClaimExpiresAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeIndexJob = `-- name: CompleteIndexJob :execrows
UPDATE index_jobs SET status = ?, error = ?, payload = '' WHERE id = ? AND status = 'running' AND claimed_by = ?
`

type CompleteIndexJobParams struct {
	Status    string
	Error     string
	ID        int64
	ClaimedBy string
}

func (q *Queries) CompleteIndexJob(ctx context.Context, arg CompleteIndexJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeIndexJob,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.ClaimedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countASTUnits = `-- name: CountASTUnits :one
SELECT COUNT(*) FROM ast_units
`

func (q *Queries) CountASTUnits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countASTUnits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countASTUnitsByRepo = `-- name: CountASTUnitsByRepo :one
SELECT COUNT(*) FROM ast_units WHERE repo_id = ?
`

func (q *Queries) CountASTUnitsByRepo(ctx context.Context, repoID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countASTUnitsByRepo, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteASTUnitsByKind = `-- name: DeleteASTUnitsByKind :exec
DELETE FROM ast_units WHERE repo_id = ? AND kind = ?
`

type DeleteASTUnitsByKindParams struct {
	RepoID string
	Kind   string
}

func (q *Queries) DeleteASTUnitsByKind(ctx context.Context, arg DeleteASTUnitsByKindParams) error {
	_, err := q.db.ExecContext(ctx, deleteASTUnitsByKind, arg.RepoID, arg.Kind)
	return err
}

const deleteASTUnitsByRepo = `-- name: DeleteASTUnitsByRepo :exec
DELETE FROM ast_units WHERE repo_id = ?
`

func (q *Queries) DeleteASTUnitsByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.ExecContext(ctx, deleteASTUnitsByRepo, repoID)
	return err
}

const deleteEdgesByFile = `-- name: DeleteEdgesByFile :exec
DELETE FROM edges WHERE repo_id = ? AND file_path = ?
`

type DeleteEdgesByFileParams struct {
	RepoID   string
	FilePath string
}

func (q *Queries) DeleteEdgesByFile(ctx context.Context, arg DeleteEdgesByFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByFile, arg.RepoID, arg.FilePath)
	return err
}

const deleteEdgesByKind = `-- name: DeleteEdgesByKind :exec
DELETE FROM edges WHERE repo_id = ? AND kind = ?
`

type DeleteEdgesByKindParams struct {
	RepoID string
	Kind   string
}

func (q *Queries) DeleteEdgesByKind(ctx context.Context, arg DeleteEdgesByKindParams) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByKind, arg.RepoID, arg.Kind)
	return err
}

const deleteEdgesByKindAndDst = `-- name: DeleteEdgesByKindAndDst :exec
DELETE FROM edges WHERE kind = ? AND dst_name = ?
`

type DeleteEdgesByKindAndDstParams struct {
	Kind    string
	DstName string
}

func (q *Queries) DeleteEdgesByKindAndDst(ctx context.Context, arg DeleteEdgesByKindAndDstParams) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByKindAndDst, arg.Kind, arg.DstName)
	return err
}

const deleteEdgesByKindGlobal = `-- name: DeleteEdgesByKindGlobal :exec
DELETE FROM edges WHERE kind = ?
`

func (q *Queries) DeleteEdgesByKindGlobal(ctx context.Context, kind string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByKindGlobal, kind)
	return err
}

const deleteEdgesByRepo = `-- name: DeleteEdgesByRepo :exec
DELETE FROM edges WHERE repo_id = ?
`

func (q *Queries) DeleteEdgesByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByRepo, repoID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE repo_id = ? AND path = ?
`

type DeleteFileParams struct {
	RepoID string
	Path   string
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.RepoID, arg.Path)
	return err
}

const deleteFilesByRepo = `-- name: DeleteFilesByRepo :exec
DELETE FROM files WHERE repo_id = ?
`

func (q *Queries) DeleteFilesByRepo(ctx context.Context, repoID string) error {
	_, err := q.db.ExecContext(ctx, deleteFilesByRepo, repoID)
	return err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const deleteRepoCoverage = `-- name: DeleteRepoCoverage :exec
DELETE FROM repo_coverage WHERE repo_id = ?
`

func (q *Queries) DeleteRepoCoverage(ctx context.Context, repoID string) error {
	_, err := q.db.ExecContext(ctx, deleteRepoCoverage, repoID)
	return err
}

const enqueueCommitJob = `-- name: EnqueueCommitJob :one

INSERT INTO index_jobs (repo_id, kind, force, status, created_at, payload)
VALUES (?, 'commits', 0, 'pending', ?, ?)
RETURNING id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
`

type EnqueueCommitJobParams struct {
	RepoID    string
	CreatedAt int64
	Payload   string
}

type EnqueueCommitJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       int64
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

// --- Index jobs ---
func (q *Queries) EnqueueCommitJob(ctx context.Context, arg EnqueueCommitJobParams) (EnqueueCommitJobRow, error) {
	row := q.db.QueryRowContext(ctx, enqueueCommitJob, arg.RepoID, arg.CreatedAt, arg.Payload)
	var i EnqueueCommitJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
	)
	return i, err
}

const getASTUnitByID = `-- name: GetASTUnitByID :one
SELECT id, repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta
FROM ast_units WHERE id = ?
`

func (q *Queries) GetASTUnitByID(ctx context.Context, id int64) (AstUnit, error) {
	row := q.db.QueryRowContext(ctx, getASTUnitByID, id)
	var i AstUnit
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.FilePath,
		&i.Language,
		&i.Kind,
		&i.Name,
		&i.Qualified,
		&i.ParentID,
		&i.StartLine,
		&i.EndLine,
		&i.StartByte,
		&i.EndByte,
		&i.Signature,
		&i.Doc,
		&i.Hash,
		&i.Meta,
	)
	return i, err
}

const getASTUnitByQualifiedName = `-- name: GetASTUnitByQualifiedName :one
SELECT id, repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta
FROM ast_units WHERE qualified = ? AND repo_id = ?
`

type GetASTUnitByQualifiedNameParams struct {
	Qualified string
	RepoID    string
}

func (q *Queries) GetASTUnitByQualifiedName(ctx context.Context, arg GetASTUnitByQualifiedNameParams) (AstUnit, error) {
	row := q.db.QueryRowContext(ctx, getASTUnitByQualifiedName, arg.Qualified, arg.RepoID)
	var i AstUnit
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.FilePath,
		&i.Language,
		&i.Kind,
		&i.Name,
		&i.Qualified,
		&i.ParentID,
		&i.StartLine,
		&i.EndLine,
		&i.StartByte,
		&i.EndByte,
		&i.Signature,
		&i.Doc,
		&i.Hash,
		&i.Meta,
	)
	return i, err
}

const getEdge = `-- name: GetEdge :one
SELECT id, repo_id, src_id, dst_id, kind, dst_name, file_path, line, dst_repo_id, confidence, meta
FROM edges WHERE id = ?
`

func (q *Queries) GetEdge(ctx context.Context, id int64) (Edge, error) {
	row := q.db.QueryRowContext(ctx, getEdge, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.SrcID,
		&i.DstID,
		&i.Kind,
		&i.DstName,
		&i.FilePath,
		&i.Line,
		&i.DstRepoID,
		&i.Confidence,
		&i.Meta,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT repo_id, path, language, hash, size, mod_time, indexed
FROM files WHERE repo_id = ? AND path = ?
`

type GetFileParams struct {
	RepoID string
	Path   string
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.RepoID, arg.Path)
	var i File
	err := row.Scan(
		&i.RepoID,
		&i.Path,
		&i.Language,
		&i.Hash,
		&i.Size,
		&i.ModTime,
		&i.Indexed,
	)
	return i, err
}

const getFilesByHash = `-- name: GetFilesByHash :many
SELECT repo_id, path, language, hash, size, mod_time, indexed
FROM files WHERE repo_id = ? AND hash = ?
`

type GetFilesByHashParams struct {
	RepoID string
	Hash   string
}

func (q *Queries) GetFilesByHash(ctx context.Context, arg GetFilesByHashParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByHash, arg.RepoID, arg.Hash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.RepoID,
			&i.Path,
			&i.Language,
			&i.Hash,
			&i.Size,
			&i.ModTime,
			&i.Indexed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByRepo = `-- name: GetFilesByRepo :many
SELECT repo_id, path, language, hash, size, mod_time, indexed
FROM files WHERE repo_id = ? ORDER BY path
`

func (q *Queries) GetFilesByRepo(ctx context.Context, repoID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.RepoID,
			&i.Path,
			&i.Language,
			&i.Hash,
			&i.Size,
			&i.ModTime,
			&i.Indexed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexJob = `-- name: GetIndexJob :one
SELECT id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
FROM index_jobs WHERE id = ?
`

type GetIndexJobRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       int64
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

func (q *Queries) GetIndexJob(ctx context.Context, id int64) (GetIndexJobRow, error) {
	row := q.db.QueryRowContext(ctx, getIndexJob, id)
	var i GetIndexJobRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Kind,
		&i.Force,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.HeartbeatAt,
		&i.ClaimedBy,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos WHERE id = ?
`

type GetRepoRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        int64
}

func (q *Queries) GetRepo(ctx context.Context, id string) (GetRepoRow, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i GetRepoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Url,
		&i.Path,
		&i.Branch,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.IndexedAt,
		&i.LastCommit,
		&i.PendingCommit,
		&i.Active,
	)
	return i, err
}

const getRepoCoverage = `-- name: GetRepoCoverage :many
SELECT kind, candidates, edges, updated_at FROM repo_coverage WHERE repo_id = ? ORDER BY kind
`

type GetRepoCoverageRow struct {
	Kind       string
	Candidates int64
	Edges      int64
	UpdatedAt  int64
}

func (q *Queries) GetRepoCoverage(ctx context.Context, repoID string) ([]GetRepoCoverageRow, error) {
	rows, err := q.db.QueryContext(ctx, getRepoCoverage, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepoCoverageRow
	for rows.Next() {
		var i GetRepoCoverageRow
		if err := rows.Scan(
			&i.Kind,
			&i.Candidates,
			&i.Edges,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingCommitJobBefore = `-- name: HasPendingCommitJobBefore :one
SELECT EXISTS(
    SELECT 1 FROM index_jobs
    WHERE repo_id = ? AND kind = 'commits' AND status IN ('pending', 'running') AND id < ?
)
`

type HasPendingCommitJobBeforeParams struct {
	RepoID string
	ID     int64
}

func (q *Queries) HasPendingCommitJobBefore(ctx context.Context, arg HasPendingCommitJobBeforeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPendingCommitJobBefore, arg.RepoID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeatIndexJob = `-- name: HeartbeatIndexJob :execrows
UPDATE index_jobs SET heartbeat_at = ? WHERE id = ? AND status = 'running' AND claimed_by = ?
`

type HeartbeatIndexJobParams struct {
	HeartbeatAt int64
	ID          int64
	ClaimedBy   string
}

func (q *Queries) HeartbeatIndexJob(ctx context.Context, arg HeartbeatIndexJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatIndexJob, arg.HeartbeatAt, arg.ID, arg.ClaimedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertASTUnit = `-- name: InsertASTUnit :one

INSERT INTO ast_units (repo_id, file_path, language, kind, name, qualified, parent_id, start_line, end_line, start_byte, end_byte, signature, doc, hash, meta)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertASTUnitParams struct {
	RepoID    string
	FilePath  string
	Language  string
	Kind      string
	Name      string
	Qualified string
	ParentID  sql.NullInt64
	StartLine int64
	EndLine   int64
	StartByte int64
	EndByte   int64
	Signature string
	Doc       string
	Hash      string
	Meta      string
}

// --- AST units ---
func (q *Queries) InsertASTUnit(ctx context.Context, arg InsertASTUnitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertASTUnit,
		arg.RepoID,
		arg.FilePath,
		arg.Language,
		arg.Kind,
		arg.Name,
		arg.Qualified,
		arg.ParentID,
		arg.StartLine,
		arg.EndLine,
		arg.StartByte,
		arg.EndByte,
		arg.Signature,
		arg.Doc,
		arg.Hash,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEdge = `-- name: InsertEdge :one

INSERT INTO edges (repo_id, src_id, dst_id, kind, dst_name, file_path, line, dst_repo_id, confidence, meta)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertEdgeParams struct {
	RepoID     string
	SrcID      int64
	DstID      int64
	Kind       string
	DstName    string
	FilePath   string
	Line       int64
	DstRepoID  string
	Confidence float64
	Meta       string
}

// --- Edges ---
func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEdge,
		arg.RepoID,
		arg.SrcID,
		arg.DstID,
		arg.Kind,
		arg.DstName,
		arg.FilePath,
		arg.Line,
		arg.DstRepoID,
		arg.Confidence,
		arg.Meta,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRepoCoverage = `-- name: InsertRepoCoverage :exec

INSERT INTO repo_coverage (repo_id, kind, candidates, edges, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRepoCoverageParams struct {
	RepoID     string
	Kind       string
	Candidates int64
	Edges      int64
	UpdatedAt  int64
}

// --- Coverage ---
func (q *Queries) InsertRepoCoverage(ctx context.Context, arg InsertRepoCoverageParams) error {
	_, err := q.db.ExecContext(ctx, insertRepoCoverage,
		arg.RepoID,
		arg.Kind,
		arg.Candidates,
		arg.Edges,
		arg.UpdatedAt,
	)
	return err
}

const listActiveRepos = `-- name: ListActiveRepos :many
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos WHERE active = 1 ORDER BY created_at
`

type ListActiveReposRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        int64
}

func (q *Queries) ListActiveRepos(ctx context.Context) ([]ListActiveReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveReposRow
	for rows.Next() {
		var i ListActiveReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Url,
			&i.Path,
			&i.Branch,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.LastCommit,
			&i.PendingCommit,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexJobs = `-- name: ListIndexJobs :many
SELECT id, repo_id, kind, force, status, error, created_at, claimed_at, heartbeat_at, claimed_by
FROM index_jobs WHERE repo_id = ? ORDER BY id DESC LIMIT ?
`

type ListIndexJobsParams struct {
	RepoID string
	Limit  int64
}

type ListIndexJobsRow struct {
	ID          int64
	RepoID      string
	Kind        string
	Force       int64
	Status      string
	Error       string
	CreatedAt   int64
	ClaimedAt   int64
	HeartbeatAt int64
	ClaimedBy   string
}

func (q *Queries) ListIndexJobs(ctx context.Context, arg ListIndexJobsParams) ([]ListIndexJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIndexJobs, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexJobsRow
	for rows.Next() {
		var i ListIndexJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Kind,
			&i.Force,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.HeartbeatAt,
			&i.ClaimedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit, pending_commit, active
FROM repos ORDER BY created_at
`

type ListReposRow struct {
	ID            string
	Name          string
	Source        string
	Url           string
	Path          string
	Branch        string
	Status        string
	LastError     string
	CreatedAt     int64
	IndexedAt     int64
	LastCommit    string
	PendingCommit string
	Active        int64
}

func (q *Queries) ListRepos(ctx context.Context) ([]ListReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReposRow
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Url,
			&i.Path,
			&i.Branch,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.IndexedAt,
			&i.LastCommit,
			&i.PendingCommit,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repoExists = `-- name: RepoExists :one
SELECT EXISTS(SELECT 1 FROM repos WHERE id = ?)
`

func (q *Queries) RepoExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, repoExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const resetExpiredIndexingRepos = `-- name: ResetExpiredIndexingRepos :execrows
UPDATE repos SET status = 'idle', claimed_by = '', claim_expires_at = 0,
    pending_commit = '', last_error = ?
WHERE status = 'indexing' AND claim_expires_at <= ?
`

type ResetExpiredIndexingReposParams struct {
	LastError      string
	ClaimExpiresAt int64
}

func (q *Queries) ResetExpiredIndexingRepos(ctx context.Context, arg ResetExpiredIndexingReposParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetExpiredIndexingRepos, arg.LastError, arg.ClaimExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetIndexingRepos = `-- name: ResetIndexingRepos :execrows
UPDATE repos SET status = 'idle', claimed_by = '', claim_expires_at = 0,
    pending_commit = '', last_error = ?
WHERE status = 'indexing'
`

func (q *Queries) ResetIndexingRepos(ctx context.Context, lastError string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetIndexingRepos, lastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveEdges = `-- name: ResolveEdges :exec
UPDATE edges SET dst_id = ? WHERE dst_id = 0 AND repo_id = ? AND dst_name = ? AND kind = ?
`

type ResolveEdgesParams struct {
	DstID   int64
	RepoID  string
	DstName string
	Kind    string
}

func (q *Queries) ResolveEdges(ctx context.Context, arg ResolveEdgesParams) error {
	_, err := q.db.ExecContext(ctx, resolveEdges,
		arg.DstID,
		arg.RepoID,
		arg.DstName,
		arg.Kind,
	)
	return err
}

const setRepoPendingCommit = `-- name: SetRepoPendingCommit :execrows
UPDATE repos SET pending_commit = ? WHERE id = ?
`

type SetRepoPendingCommitParams struct {
	PendingCommit string
	ID            string
}

func (q *Queries) SetRepoPendingCommit(ctx context.Context, arg SetRepoPendingCommitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRepoPendingCommit, arg.PendingCommit, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const storeFile = `-- name: StoreFile :exec


INSERT INTO files (repo_id, path, language, hash, size, mod_time, indexed)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repo_id, path) DO UPDATE SET
    language = excluded.language, hash = excluded.hash,
    size = excluded.size, mod_time = excluded.mod_time, indexed = excluded.indexed
`

type StoreFileParams struct {
	RepoID   string
	Path     string
	Language string
	Hash     string
	Size     int64
	ModTime  int64
	Indexed  int64
}

// Static queries for the SQLite backend, compiled by sqlc into the sqlite
// package. The dynamic filtered queries (GetASTUnits/GetEdges over QueryOpts)
// and the batched/transactional writers are hand-written in their .go files;
// sqlc cannot express those.
//
// Booleans are stored as INTEGER (0/1): the wrappers convert to/from Go bool.
// --- Files ---
func (q *Queries) StoreFile(ctx context.Context, arg StoreFileParams) error {
	_, err := q.db.ExecContext(ctx, storeFile,
		arg.RepoID,
		arg.Path,
		arg.Language,
		arg.Hash,
		arg.Size,
		arg.ModTime,
		arg.Indexed,
	)
	return err
}

const storeRepo = `-- name: StoreRepo :exec

INSERT INTO repos (id, name, source, url, path, branch, status, last_error, created_at, indexed_at, last_commit)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name, source = excluded.source, url = excluded.url,
    path = excluded.path, branch = excluded.branch
`

type StoreRepoParams struct {
	ID         string
	Name       string
	Source     string
	Url        string
	Path       string
	Branch     string
	Status     string
	LastError  string
	CreatedAt  int64
	IndexedAt  int64
	LastCommit string
}

// --- Repos ---
func (q *Queries) StoreRepo(ctx context.Context, arg StoreRepoParams) error {
	_, err := q.db.ExecContext(ctx, storeRepo,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Url,
		arg.Path,
		arg.Branch,
		arg.Status,
		arg.LastError,
		arg.CreatedAt,
		arg.IndexedAt,
		arg.LastCommit,
	)
	return err
}

const updateEdgeDstName = `-- name: UpdateEdgeDstName :execrows
UPDATE edges SET dst_name = ? WHERE id = ?
`

type UpdateEdgeDstNameParams struct {
	DstName string
	ID      int64
}

func (q *Queries) UpdateEdgeDstName(ctx context.Context, arg UpdateEdgeDstNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEdgeDstName, arg.DstName, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEdgeMeta = `-- name: UpdateEdgeMeta :execrows
UPDATE edges SET meta = ? WHERE id = ?
`

type UpdateEdgeMetaParams struct {
	Meta string
	ID   int64
}

func (q *Queries) UpdateEdgeMeta(ctx context.Context, arg UpdateEdgeMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEdgeMeta, arg.Meta, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEdgeResolution = `-- name: UpdateEdgeResolution :execrows
UPDATE edges SET dst_id = ?, dst_repo_id = ?, confidence = ? WHERE id = ?
`

type UpdateEdgeResolutionParams struct {
	DstID      int64
	DstRepoID  string
	Confidence float64
	ID         int64
}

func (q *Queries) UpdateEdgeResolution(ctx context.Context, arg UpdateEdgeResolutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEdgeResolution,
		arg.DstID,
		arg.DstRepoID,
		arg.Confidence,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRepoLastCommit = `-- name: UpdateRepoLastCommit :execrows
UPDATE repos SET last_commit = ? WHERE id = ?
`

type UpdateRepoLastCommitParams struct {
	LastCommit string
	ID         string
}

func (q *Queries) UpdateRepoLastCommit(ctx context.Context, arg UpdateRepoLastCommitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRepoLastCommit, arg.LastCommit, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRepoStatus = `-- name: UpdateRepoStatus :execrows
UPDATE repos SET status = ?, last_error = ?, indexed_at = ?,
    claimed_by = '', claim_expires_at = 0, pending_commit = ''
WHERE id = ?
`

type UpdateRepoStatusParams struct {
	Status    string
	LastError string
	IndexedAt int64
	ID        string
}

func (q *Queries) UpdateRepoStatus(ctx context.Context, arg UpdateRepoStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRepoStatus,
		arg.Status,
		arg.LastError,
		arg.IndexedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
